name: 'build and deploy production'

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build-prd-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js version 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci

      - name: Run build production (create dist folder)
        run: npm run build

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-prd
          path: dist
