name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        name: Setup Node.js version 18
        with:
          node-version: '18.x'
      - run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Format
        run: npm run format
